sonar.projectKey=sangkp52_ecommerce
sonar.organization=sangkp52
sonar.host.url=https://sonarcloud.io
sonar.python.version=3.11
sonar.projectBaseDir=backend
sonar.sources=src
sonar.python.coverage.reportPaths=coverage.xml