env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: CI Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
     mongo:
        image: mongo:6.0
        ports:
          - 27017:27017   # port host:port container
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI: mongodb://localhost:27017
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

    # - name: Install SonarScanner
    #   uses: sonarsource/sonarcloud-github-action@v2
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     args: >
    #       -Dsonar.projectKey=sangkp52_ecommerce
    #       -Dsonar.organization=sangkp52
    #       -Dsonar.sources=backend

    # - name: Run unit tests
    #   run: |
    #     cd backend
    #     pytest tests/unit -v

    # - name: Run integration tests
    #   run: |
    #     cd backend
    #     pytest tests/integration -v

    # - name: Run tests with coverage
    #   env:
    #     PYTHONPATH: .
    #   run: |
    #     cd backend
    #     python -m pytest --cov=src --cov-report=term-missing

    - name: Run all tests with coverage
      env:
        PYTHONPATH: .
      run: |
        cd backend
        pytest --cov=src --cov-report=xml:coverage.xml

    - name: Fix coverage report paths
      working-directory: backend/
      run: |
        sed -i 's|/home/runner/work/ecommerce/ecommerce/backend/||g' coverage.xml

    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.python.version=3.11
          -Dsonar.projectKey=sangkp52_ecommerce
          -Dsonar.organization=sangkp52
          -Dsonar.projectBaseDir=backend
          -Dsonar.sources=src
          -Dsonar.python.coverage.reportPaths=coverage.xml
          

        
  deploy-production:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render Production
        run: |
            curl -X POST ${{ secrets.RENDER_PROD_HOOK }}