env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: CI Test

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

    - name: Install SonarScanner
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=sangkp52_ecommerce
          -Dsonar.organization=sangkp52
          -Dsonar.sources=backend


    - name: Run tests
      run: |
        cd backend
        pytest -v

